#!/bin/bash

if [ ! $# -eq 2 ]
then
  echo "zla liczba argumentow"
  exit 1
fi

if [ ! -d $1 ]
then
   echo "to nie jest katalog"
   exit 1
fi

for f in $1/*
do
   if [ -f $f ] && [ -w $f ] && [ -x $f ]
   then
        touch -mt $2 $f
   fi
done

#plik, który mam istnieć mam mieć prawo zapisu i dostępu, zmienić datę modyfikacji 
